# Generated by Django 3.1 on 2020-08-20 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200816_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='image',
            new_name='profile_pic',
        ),
    ]
