# Generated by Django 3.1.4 on 2020-12-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gameDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Steam_ID', models.PositiveIntegerField()),
                ('Game_Title', models.CharField(max_length=255)),
                ('Genre', models.CharField(max_length=255)),
                ('Release_Date', models.CharField(max_length=255)),
                ('Publisher', models.CharField(max_length=255)),
                ('Price', models.CharField(max_length=255)),
                ('Languages', models.TextField()),
                ('Descriptions', models.TextField()),
                ('Mature_Content_Descriptions', models.TextField(null=True)),
                ('System_Requirements', models.TextField()),
                ('Metric_Critic_Score', models.CharField(max_length=64, null=True)),
                ('Metric_Critic_Score_Link', models.TextField(null=True)),
                ('Links', models.TextField()),
            ],
        ),
    ]
