# Generated by Django 3.1.4 on 2020-12-25 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gamedetails',
            table='Game details',
        ),
    ]
