# Generated by Django 3.1.4 on 2020-12-25 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20201225_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamedetails',
            options={'verbose_name': 'Game Detail'},
        ),
        migrations.AlterModelTable(
            name='gamedetails',
            table='Game Detail',
        ),
    ]
